Date changed 2

diff --git a/html-helloworld/.s2i/bin/assemble b/html-helloworld/.s2i/bin/assemble
--- a/html-helloworld/.s2i/bin/assemble
+++ b/html-helloworld/.s2i/bin/assemble
@@ -12,10 +12,21 @@ echo "-----------------------------------------> Personalization"
 
 /usr/libexec/s2i/assemble
 
-cp -af /tmp/html/. /var/www/html/
 
-DATE='date "+%b %d, %Y @ %H:%M %p"'
+rc=$?
+if [ $rc -eq 0 ]; then
 
-echo "---> adding date to info.html"
-echo "the {$DATE} inserted " >> /var/www/html/info.html
-sed -i s/THE-DATE/$DATE/ /var/www/html/info.html 
+   echo "Making post-invocation changes..."
+
+   cp -af /tmp/html/. /var/www/html/
+
+   DATE='date "+%b %d, %Y @ %H:%M %p"'
+
+   echo "---> adding date to info.html"
+   echo "the {$DATE} inserted " >> /var/www/html/info.html
+   sed -i s/THE-DATE/$DATE/ /var/www/html/info.html 
+else
+   echo "Error: assemble failed!"
+fi
+exit $rc
+
